version: "3"
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data: