version: "3"
services:
  api:
    container_name: spring
    hostname: spring
    build: ./spring-boot-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - rabbit
  pajton:
    container_name: fft-service
    build: 
      context: ./magnitude-spectrum-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
      - rabbit
      - api
  frontend:
    container_name: angular
    build: ./image-analyser
    restart: always
    ports:
      - 4200:80
    depends_on:
      - api
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.6-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:6.0
    ports:
      - 27017:27017
