version: "3"
services:
  api:
    container_name: api
    hostname: spring
    build: ./api
    restart: always
    environment:
      # - SPRING_PROFILES_ACTIVE=dev
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - rabbit
      - magnitude-service
  magnitude-service:
    container_name: fft-service
    build:
      context: ./fft-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
      - rabbit
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - 4200:80
    depends_on:
      - api
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    # healthcheck:
    #   test: rabbitmq-diagnostics check_port_connectivity
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:6.0
    ports:
      - 27017:27017
